### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by delvedor** [mcollina/fastify#12]
Input validation via *json-schema* using [ajv](https://github.com/epoberezkin/ajv) for perf reasons.

Ajv bench:
- [json-schema-benchmark](https://github.com/ebdrup/json-schema-benchmark)
- [jsck](https://github.com/pandastrike/jsck#benchmarks)
- [z-schema](https://rawgit.com/zaggino/z-schema/master/benchmark/results.html)
- [themis](https://cdn.rawgit.com/playlyfe/themis/master/benchmark/results.html)

**Comment by delvedor** [comment]
If the input validation fails, how we want to handle it?
Add an `err` field to request or add an `err` object into the callback?
- Req obj:
```js
fastify.get('/', schema, function (req, reply) {
  if (req.err) return reply(req.err)
  reply(null, { hello: 'world' })
})
```
- Err in callback:
```js
fastify.get('/', schema, function (err, req, reply) {
  if (err) return reply(err)
  reply(null, { hello: 'world' })
})
```

Ideas?

**Comment by mcollina** [comment]
I would not let it reach our handlers, silently drop it.

**Comment by delvedor** [comment]
You mean as it works in Hapi?

**Comment by mcollina** [comment]
Yes

**Comment by delvedor** [comment]
For me is ok, but in the future I would like give the user a choice about this.

**Comment by mcollina** [comment]
having an `err` as the first argument is a nice way to opt in this behavior.
Making this type of "opt-in" fast is very complicated.

If you want to give it a stab, feel free to :).

We should start to document things as well!

**Comment by lucamaraschi** [comment]
I would personally go for @mcollina's option, returning to the client a http status code [400](https://tools.ietf.org/html/rfc7231#section-6.5.1) error. In this way it would conform to the standard and to what most of API developers are used to.

**Comment by delvedor** [comment]
If you both guys say that is the best option I'm fine with that :)
Soon the pr.

**Comment by delvedor** [comment]
Another PR will come for `querystring` validation, keeping this open.
