### ISSUE TITLE
support streams

### ISSUE THREAD

**Issue by mcollina** [mcollina/fastify#23]
We should be able to call `reply(null, stream)`.

**Comment by marcbachmann** [comment]
Oh, nice. I just landed on this issue by accident. I also need something like that in my setup.
I guess fastify responds with `Content-Type: application/json` by default, right?
So would you only support utf8 encoded streams and the stream is responsible to support proper json?

Or would you allow a custom content type by passing it somewhere?
And then we can also support line delimited json.

e.g.
```js
fastify.get('/documents', function (opts, reply) {
  // returns a stream in object mode
  var stream = database.select('*').from('documents').toStream()

  // Set content type on stream
  stream['Content-Type'] = 'application/x-ndjson'
  reply(null, stream)
  // or
  reply(null, stream, {'Content-Type': 'application/x-ndjson'})
})
```

**Comment by mcollina** [comment]
I think we should do something with `reply`, rather than setting properties on the stream object.

**Comment by delvedor** [comment]
I'm working on stream support at the moment, the in the next days will land a pr :)
https://github.com/mcollina/fastify/tree/stream-support

**Comment by delvedor** [comment]
Stream support added in #27.

**Comment by leodutra** [comment]
Sorry for kicking these ashes, but object mode is not working or requires something not documented.
Any insight on this? 

Replication:
I have a stream of JSON, from the resolution of a promises array.
The Readable is unit tested, and it's in object mode.
Whenever I call `reply.send(stream)` I get the same typical error on `stream.push(json)` telling chunk should be string or Buffer.
