### ISSUE TITLE
url wildcard support

### ISSUE THREAD

**Issue by GavinDmello** [mcollina/fastify#24]
Are you guys planning on url wildcard support in the routes ?   I'm not sure if it's possible with the current setup .  Also, I'm not sure if it should be handled on the frame work or inside wayfarer.

**Comment by mcollina** [comment]
This project is a very good experiment! We are open to PRs :D, if you want to help and contribute.
Probably it's on wayfarer, but I think it would be welcome there as well!

**Comment by delvedor** [comment]
I think it wayfarer related, do it here means add logic that should be handled by the router :)

**Comment by GavinDmello** [comment]
Will get sorted when wayfarer solves it .

**Comment by delvedor** [comment]
Now wayfarer supports [wildcards](https://github.com/yoshuawuyts/wayfarer/pull/55), so us as well :)

**Comment by GavinDmello** [comment]
Yep. Just saw the release :)
