### ISSUE TITLE
querystring validation/parsing

### ISSUE THREAD

**Issue by brwnll** [mcollina/fastify#31]
First off, thanks for creating this, I'm very excited to see where this goes, and it has been great to work with thus far.

Question about `querystring` in the schema, it doesn't appear to be doing anything. I'm hoping you could point out what I'm missing:

Here's an example:
```js
fastify.route({
    "method": "GET",
    "url": "/list",
    "schema": {
      "querystring": {
        "limit": {
          "type": "integer"
        }
      },
      "out": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "count": {
              "type": "integer"
            }
          }
        }
      }
    }
  })
````

`req.query` outputs:

> Valid query: /list?limit=10 
> `{ limit: '10' } // Limit is a string`

> Invalid query param: /list?limit=a
> `{ limit: 'a' } // Invalid limit passed through as string`

> Extra query params: /list?limit=1&lookatme=true
> `{ limit: 'a', lookatme: 'true' }`

Hopefully you can tell me what I'm doing incorrectly, thanks.

**Comment by mcollina** [comment]
The syntax is slightly different. See https://github.com/mcollina/fastify/blob/master/test/get.test.js#L19-L28.

However, I like _your_ syntax more.
Would you like to send a PR to add the support for either better reporting or key/value type of validation.

Maybe this can help http://json-schema.org/documentation.html (we can use the meta-schema to validate that the schema is valid JSON-schema).

**Comment by brwnll** [comment]
Thanks @mcollina, worked like a charm. I'll see if I can get a PR in. I'm working off the `reply-refactor` branch, so I may wait until that PR is completed.

**Comment by mcollina** [comment]
@brwnll that might be a good idea :)
