### ISSUE TITLE
Multiple response types

### ISSUE THREAD

**Issue by brwnll** [mcollina/fastify#32]
Is there a way to define multiple response types? For example a route response my have a different structure for a success/error response.

I have a route that returns an array of objects on success, but an error object on failure.

**Comment by delvedor** [comment]
Hi! In the `reply-refactor` branch the error wiil be stringified with *fast-safe-stringify* :)

@mcollina shuould we add an error schema as well?

**Comment by mcollina** [comment]
I don't think so. It's easy to add _optional_ properties to the output schema.

**Comment by delvedor** [comment]
Yeah, but at the moment the *serialize* function is not called in case of an Error object, as said above is stringified with *fast-safe-stringify*.

**Comment by mcollina** [comment]
Let's defer this discussion to the future. The current approach is simple.
